# 一、ndarray
## 1.ndarray的特性
### 多维性

In [1]:
import numpy as np

In [5]:
arr = np.array(5)       # 创建 0 维的 ndarray 数组
print(arr)
print('arr的维度', arr.ndim)   #数组的维度 number of dimensions

5
arr的维度 0


In [6]:
arr = np.array([1, 2, 3])       # 创建 1 维的 ndarray 数组
print(arr)
print('arr的维度', arr.ndim)   #数组的维度 number of dimensions

[1 2 3]
arr的维度 1


In [8]:
arr = np.array([[1, 2, 3],[4, 5, 6]])       # 创建 2 维的 ndarray 数组
print(arr)
print('arr的维度', arr.ndim)   #数组的维度number of dimensions

[[1 2 3]
 [4 5 6]]
arr的维度 2


### 同质性

In [9]:
arr = np.array([1, 'hello'])       # 不同数据类型会被强制转换成相同数据类型
print(arr)
print('arr的维度', arr.ndim)   #数组的维度number of dimensions

['1' 'hello']
arr的维度 1


In [10]:
arr = np.array([1, 2.5])       # 不同数据类型会被强制转换成相同数据类型
print(arr)
print('arr的维度', arr.ndim)   #数组的维度number of dimensions

[1.  2.5]
arr的维度 1


## 2.ndarray 的属性
1. shape
2. ndim
3. size
4. dtype
5. T
6. itemsize
7. nbytes
8. flags

In [27]:
arr = np.array(1)
print(arr)
print('数组的形状：', arr.shape)
print('数组的维度：', arr.ndim)
print('元素的个数：', arr.size)
print('元素的类型：', arr.dtype)
print('元素的转置：', arr.T)


1
数组的形状： ()
数组的维度： 0
元素的个数： 1
元素的类型： int64
元素的转置： 1


In [28]:
arr = np.array([[1, 2.5, 3],[4, 5, 6]])
print(arr)
print('数组的形状', arr.shape)
print('数组的维度：', arr.ndim)
print('元素的个数：', arr.size)
print('元素的类型：', arr.dtype)
print('元素的转置：', arr.T)



[[1.  2.5 3. ]
 [4.  5.  6. ]]
数组的形状 (2, 3)
数组的维度： 2
元素的个数： 6
元素的类型： float64
元素的转置： [[1.  4. ]
 [2.5 5. ]
 [3.  6. ]]


In [29]:
arr = np.array(['1', '2', '3'])
print(arr)
print('数组的形状', arr.shape)
print('数组的维度：', arr.ndim)
print('元素的个数：', arr.size)
print('元素的类型：', arr.dtype)
print('元素的转置：', arr.T)




['1' '2' '3']
数组的形状 (3,)
数组的维度： 1
元素的个数： 3
元素的类型： <U1
元素的转置： ['1' '2' '3']
